const KEY="dukaan_khata_infinity_v2";
let state=loadState(),khataFilter="all",longPress=null;

function defaults(){return{shop:{name:"My Dukaan",owner:"Shop Owner",phone:"",upi:"",address:""},customers:[],tx:[],expenses:[],returns:[],reminders:[],settings:{theme:"light",language:"English"}}}
function loadState(){
  try{
    const raw=localStorage.getItem(KEY)||localStorage.getItem("dukaan_khata_infinity_v1");
    const x=raw?JSON.parse(raw):{};
    return {...defaults(),...x,shop:{...defaults().shop,...(x.shop||{})},settings:{...defaults().settings,...(x.settings||{})},
      customers:Array.isArray(x.customers)?x.customers:[],tx:Array.isArray(x.tx)?x.tx:[],
      expenses:Array.isArray(x.expenses)?x.expenses:[],returns:Array.isArray(x.returns)?x.returns:[],
      reminders:Array.isArray(x.reminders)?x.reminders:[]};
  }catch(e){return defaults()}
}
function saveState(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){toast("Could not save data")}}
function uid(){return typeof crypto!=="undefined"&&crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2)}
function money(n){return"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function balance(id){return state.tx.filter(t=>t.customerId===id).reduce((s,t)=>s+(t.type==="sale"?Number(t.total)||0:-(Number(t.amount)||0)),0)}
function sales(){return state.tx.filter(t=>t.type==="sale")}
function payments(){return state.tx.filter(t=>t.type==="payment")}
function toast(msg){const e=document.getElementById("toast");if(!e)return;e.textContent=msg;e.classList.add("show");clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove("show"),2200)}
function modal(html){const m=document.getElementById("modal"),b=document.getElementById("modalBody");if(!m||!b)return;b.innerHTML=html;m.classList.remove("hidden")}
function closeModal(){document.getElementById("modal")?.classList.add("hidden")}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(id)?.classList.add("active");document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===id));render()}
function openSearch(){modal('<h2>Search</h2><input id="globalSearch" placeholder="Customer or phone..." autocomplete="off"><div id="globalResults"></div>');document.getElementById("globalSearch")?.addEventListener("input",globalResults);globalResults();document.getElementById("globalSearch")?.focus()}
function globalResults(){const q=(document.getElementById("globalSearch")?.value||"").toLowerCase();const box=document.getElementById("globalResults");if(!box)return;const a=state.customers.filter(c=>(c.name+" "+c.phone).toLowerCase().includes(q)).slice(0,10);box.innerHTML=a.map(c=>'<div class="customer" onclick="closeModal();customerView(\''+esc(c.id)+'\')"><div><b>'+esc(c.name)+'</b><small>'+esc(c.phone||"")+'</small></div><b>'+money(balance(c.id))+'</b></div>').join("")||'<p class="muted">No customers found.</p>'}

function addCustomer(mode=""){modal('<h2>New Customer</h2><input id="cname" placeholder="Customer name" autocomplete="name"><input id="cphone" inputmode="tel" placeholder="Mobile / WhatsApp number"><textarea id="caddress" placeholder="Address (optional)"></textarea><button class="btn primary" id="saveCustomerBtn">Save Customer</button>');document.getElementById("saveCustomerBtn")?.addEventListener("click",()=>saveCustomer(mode))}
function saveCustomer(mode=""){const name=(document.getElementById("cname")?.value||"").trim();if(!name)return toast("Enter customer name");const c={id:uid(),name,phone:(document.getElementById("cphone")?.value||"").trim(),address:(document.getElementById("caddress")?.value||"").trim(),created:new Date().toISOString()};state.customers.unshift(c);saveState();closeModal();render();toast("Customer added");if(mode==="many")openManyItems(c.id);if(mode==="many-picker")openManyItems()}
function editCustomer(id){const c=state.customers.find(x=>x.id===id);if(!c)return;modal('<h2>Edit Customer</h2><input id="editCName" value="'+esc(c.name)+'" placeholder="Customer name"><input id="editCPhone" value="'+esc(c.phone)+'" inputmode="tel" placeholder="Mobile number"><textarea id="editCAddress" placeholder="Address">'+esc(c.address)+'</textarea><button class="btn primary" id="editCustomerBtn">Save Customer</button>');document.getElementById("editCustomerBtn")?.addEventListener("click",()=>saveCustomerEdit(id))}
function saveCustomerEdit(id){const c=state.customers.find(x=>x.id===id);if(!c)return;const name=(document.getElementById("editCName")?.value||"").trim();if(!name)return toast("Enter customer name");c.name=name;c.phone=(document.getElementById("editCPhone")?.value||"").trim();c.address=(document.getElementById("editCAddress")?.value||"").trim();saveState();closeModal();render();toast("Customer updated")}
function addCustomerNumber(id){editCustomer(id)}

function openManyItems(customerId){
  if(!state.customers.length)return addCustomer("many-picker");
  if(!customerId){
    const cards=state.customers.map(c=>'<button type="button" class="customer sell-customer-choice" data-customer-id="'+esc(c.id)+'"><span><b>'+esc(c.name)+'</b><small>'+esc(c.phone||"No phone added")+'</small></span><strong>›</strong></button>').join("");
    modal('<h2>＋ New Sell</h2><p class="muted">Select a customer. All your customers are shown below.</p><div id="sellCustomerList">'+cards+'</div><button class="btn primary" id="addSellCustomerBtn">＋ Add New Customer</button>');
    document.querySelectorAll(".sell-customer-choice").forEach(btn=>btn.addEventListener("click",()=>showManyItemsForm(btn.dataset.customerId)));
    document.getElementById("addSellCustomerBtn")?.addEventListener("click",()=>addCustomer("many-picker"));
    return
  }
  showManyItemsForm(customerId)
}
function openSale(customerId){openManyItems(customerId)}
function showManyItemsForm(customerId){
  const c=state.customers.find(x=>x.id===customerId);if(!c)return;
  modal('<h2>＋ Add Items</h2><p><b>'+esc(c.name)+'</b></p><button class="btn small" id="changeSellCustomerBtn">↔ Change Customer</button><div id="manyRows"></div><button class="btn" id="addManyRowBtn">＋ Add another item</button><div class="line"><b>Total</b><b id="manyTotal">₹0</b></div><button class="btn primary" id="saveManyBtn">Save to Khata</button>');
  document.getElementById("changeSellCustomerBtn")?.addEventListener("click",()=>openManyItems());
  document.getElementById("addManyRowBtn")?.addEventListener("click",addManyRow);
  document.getElementById("saveManyBtn")?.addEventListener("click",()=>saveManyItems(customerId));addManyRow()
}
function addManyRow(){const box=document.getElementById("manyRows");if(!box)return;const row=document.createElement("div");row.className="row many-row";row.style.margin="8px 0";row.innerHTML='<input class="many-name" placeholder="Item name" autocomplete="off"><input class="many-price" type="number" min="0.01" step="0.01" placeholder="Price"><button class="btn small many-remove" type="button">✕</button>';box.appendChild(row);row.querySelector(".many-price")?.addEventListener("input",recalcManyItems);row.querySelector(".many-remove")?.addEventListener("click",()=>{row.remove();recalcManyItems()});recalcManyItems()}
function recalcManyItems(){let total=0;document.querySelectorAll("#manyRows .many-row").forEach(r=>total+=Math.max(0,Number(r.querySelector(".many-price")?.value)||0));const e=document.getElementById("manyTotal");if(e)e.textContent=money(total)}
function saveManyItems(customerId){const lines=[];document.querySelectorAll("#manyRows .many-row").forEach(r=>{const name=(r.querySelector(".many-name")?.value||"").trim(),price=Number(r.querySelector(".many-price")?.value)||0;if(name&&price>0)lines.push({name,qty:1,price,total:price})});if(!lines.length)return toast("Add item name and price");const total=lines.reduce((s,x)=>s+x.total,0);state.tx.unshift({id:uid(),type:"sale",customerId,total,paid:0,mode:"credit",lines,date:new Date().toISOString()});saveState();closeModal();render();toast("Items saved to Khata")}

function customerView(id){const c=state.customers.find(x=>x.id===id);if(!c)return;const b=balance(id),tx=state.tx.filter(t=>t.customerId===id).slice(0,50);const items=[];tx.filter(t=>t.type==="sale").forEach(t=>(t.lines||[]).forEach(l=>items.push('<div class="line"><span>🧾 '+esc(l.name)+' × '+(Number(l.qty)||1)+'</span><b>'+money(l.total)+'</b></div>')));const history=tx.map(t=>t.type==="sale"?'<div class="card" data-long-delete data-delete-type="transaction" data-delete-id="'+esc(t.id)+'"><div class="line"><span>Sale</span><b>'+money(t.total)+'</b></div><small>'+esc((t.lines||[]).map(l=>l.name+" × "+l.qty).join(" • "))+'</small></div>':'<div class="line" data-long-delete data-delete-type="transaction" data-delete-id="'+esc(t.id)+'"><span>Payment • '+esc(t.mode||"")+'</span><b>'+money(t.amount)+'</b></div>').join("")||'<p class="muted">No transactions yet.</p>';modal('<h2>'+esc(c.name)+'</h2><p>'+esc(c.phone||"No phone added")+'</p><div class="'+(b>0?"due":"paid")+'" style="font-size:28px;margin:10px 0">'+money(b)+' <small>'+(b>0?"due":"clear")+'</small></div><button class="btn primary" onclick="openManyItems(\''+esc(id)+'\')">＋ Add Items to Khata</button><h3>Items in Khata</h3>'+(items.join("")||'<p class="muted">No items yet.</p>')+'<div class="row"><button class="btn" onclick="editCustomer(\''+esc(id)+'\')">✎ Edit / Add Number</button><button class="btn" onclick="openReceive(\''+esc(id)+'\')">⌁ Receive</button></div><div class="row"><button class="btn" onclick="shareCustomer(\''+esc(id)+'\')">💬 WhatsApp</button><button class="btn" onclick="callCustomer(\''+esc(id)+'\')">☎ Call</button></div><h3>History</h3>'+history+'<button class="btn" style="background:#dc2626" onclick="deleteCustomer(\''+esc(id)+'\')">Delete Customer</button>')}
function deleteCustomer(id){const c=state.customers.find(x=>x.id===id);if(!c)return;if(!confirm("Delete "+c.name+" and its khata history?"))return;state.customers=state.customers.filter(x=>x.id!==id);state.tx=state.tx.filter(x=>x.customerId!==id);state.reminders=state.reminders.filter(x=>x.customerId!==id);saveState();closeModal();render();toast("Customer deleted")}

function openReceive(customerId=""){const opts=state.customers.map(c=>'<option value="'+esc(c.id)+'" '+(c.id===customerId?"selected":"")+'>'+esc(c.name)+'</option>').join("");modal('<h2>Smart Receive</h2><div class="receive-tabs"><button class="active" id="qrTab">UPI QR</button><button id="recordTab">Record payment</button></div><div id="receiveQR"><p class="muted">UPI QR for your shop.</p><input id="qrAmount" type="number" min="1" placeholder="Amount (optional)"><div class="qr-card"><div id="qrBox"></div><b id="qrCaption">'+esc(state.shop.upi||"Add UPI ID in Shop Profile")+'</b></div><div class="row"><button class="btn primary" id="sharePayBtn">↗ Share</button><button class="btn" id="copyPayBtn">Copy UPI link</button></div></div><div id="receiveRecord" class="hidden"><select id="payCustomer"><option value="">Walk-in / Other</option>'+opts+'</select><input id="payAmount" type="number" min="1" placeholder="Amount received"><select id="payMode"><option value="cash">Cash</option><option value="upi">UPI</option><option value="bank">Bank</option><option value="card">Card</option></select><button class="btn primary" id="savePaymentBtn">Save Payment</button></div>');
  const qr=document.getElementById("qrTab"),rec=document.getElementById("recordTab"),a=document.getElementById("receiveQR"),b=document.getElementById("receiveRecord");
  qr?.addEventListener("click",()=>{qr.classList.add("active");rec?.classList.remove("active");a?.classList.remove("hidden");b?.classList.add("hidden");refreshQR()});
  rec?.addEventListener("click",()=>{rec.classList.add("active");qr?.classList.remove("active");b?.classList.remove("hidden");a?.classList.add("hidden")});
  document.getElementById("qrAmount")?.addEventListener("input",refreshQR);document.getElementById("sharePayBtn")?.addEventListener("click",sharePaymentLink);document.getElementById("copyPayBtn")?.addEventListener("click",copyUPILink);document.getElementById("savePaymentBtn")?.addEventListener("click",savePayment);setTimeout(refreshQR,50)
}
function upiLink(){const id=(state.shop.upi||"").trim();if(!id)return"";const a=Number(document.getElementById("qrAmount")?.value||0);return"upi://pay?pa="+encodeURIComponent(id)+"&pn="+encodeURIComponent(state.shop.name)+"&cu=INR"+(a>0?"&am="+a:"")}
function refreshQR(){const box=document.getElementById("qrBox"),cap=document.getElementById("qrCaption");if(!box)return;box.innerHTML="";const link=upiLink();if(!link){box.innerHTML='<div class="qr-empty">Add UPI ID in Shop Profile</div>';if(cap)cap.textContent="No UPI ID configured";return}if(window.QRCode)new QRCode(box,{text:link,width:190,height:190});else box.innerHTML='<div class="qr-empty">QR library unavailable.<br>Use Copy UPI link.</div>';if(cap)cap.textContent=state.shop.upi}
function copyUPILink(){const x=upiLink();if(!x)return toast("Add UPI ID first");if(navigator.clipboard?.writeText)navigator.clipboard.writeText(x).then(()=>toast("UPI link copied")).catch(()=>toast(x));else toast(x)}
function sharePaymentLink(){const x=upiLink();if(!x)return toast("Add UPI ID first");const text="Pay "+state.shop.name+"\n"+x;if(navigator.share)navigator.share({title:"Payment",text}).catch(()=>{});else window.open("https://wa.me/?text="+encodeURIComponent(text),"_blank")}
function savePayment(){const amount=Number(document.getElementById("payAmount")?.value)||0;if(amount<=0)return toast("Enter a valid amount");state.tx.unshift({id:uid(),type:"payment",customerId:document.getElementById("payCustomer")?.value||"",amount,mode:document.getElementById("payMode")?.value||"cash",date:new Date().toISOString()});saveState();closeModal();render();toast("Payment recorded")}

function shareCustomer(id){const c=state.customers.find(x=>x.id===id),p=(c?.phone||"").replace(/\D/g,"");if(!p)return toast("Add customer phone first");window.open("https://wa.me/"+(p.length===10?"91":"")+p+"?text="+encodeURIComponent("Hello "+c.name+" 👋 Your Dukaan Khata balance is "+money(balance(id))+".") ,"_blank")}
function callCustomer(id){const p=(state.customers.find(x=>x.id===id)?.phone||"").replace(/\D/g,"");if(!p)return toast("Add customer phone first");location.href="tel:"+p}
function remindCustomer(id){const c=state.customers.find(x=>x.id===id);if(!c||balance(id)<=0)return toast("No due balance");const p=(c.phone||"").replace(/\D/g,"");state.reminders.unshift({id:uid(),customerId:id,amount:balance(id),date:new Date().toISOString()});saveState();if(p)window.open("https://wa.me/"+(p.length===10?"91":"")+p+"?text="+encodeURIComponent("Reminder from "+state.shop.name+": outstanding "+money(balance(id))),"_blank");toast("Reminder prepared")}
function openCustomerHub(){if(!state.customers.length)return modal('<h2>Customer Connect</h2><p>No customers yet.</p><button class="btn primary" onclick="closeModal();addCustomer()">＋ Add Customer</button>');const opts=state.customers.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join("");modal('<h2>Customer Connect</h2><select id="hubCustomer">'+opts+'</select><button class="btn" onclick="shareCustomer(document.getElementById(\'hubCustomer\').value)">💬 WhatsApp</button><button class="btn" onclick="callCustomer(document.getElementById(\'hubCustomer\').value)">☎ Call</button><button class="btn" onclick="remindCustomer(document.getElementById(\'hubCustomer\').value)">🔔 Remind</button><button class="btn" onclick="customerView(document.getElementById(\'hubCustomer\').value)">◉ Open Customer</button>')}
function openReminderCenter(){const a=state.customers.filter(c=>balance(c.id)>0);modal('<h2>Reminder Center</h2>'+(a.map(c=>'<div class="customer"><div><b>'+esc(c.name)+'</b><small>Due '+money(balance(c.id))+'</small></div><button class="btn small" onclick="remindCustomer(\''+esc(c.id)+'\')">🔔 Remind</button></div>').join("")||'<p class="muted">No outstanding customers.</p>'))}
function openDigitalPass(){modal('<h2>✦ Digital Shop Pass</h2><div class="digital-pass"><div class="pass-logo">₹</div><h3>'+esc(state.shop.name)+'</h3><p>'+esc(state.shop.owner)+'</p><p>'+esc(state.shop.address||"Indian small business")+'</p><b>'+esc(state.shop.upi||"UPI not configured")+'</b></div><button class="btn primary" onclick="shareShopPass()">↗ Share Shop Pass</button>')}
function shareShopPass(){const text=state.shop.name+"\n"+(state.shop.address||"")+"\nUPI: "+(state.shop.upi||"Not configured");if(navigator.share)navigator.share({title:state.shop.name,text}).catch(()=>{});else window.open("https://wa.me/?text="+encodeURIComponent(text),"_blank")}

function openShopSettings(){const s=state.shop;modal('<h2>Shop Profile</h2><input id="shopName" value="'+esc(s.name)+'" placeholder="Shop name"><input id="shopOwner" value="'+esc(s.owner)+'" placeholder="Owner name"><input id="shopPhone" value="'+esc(s.phone)+'" placeholder="Shop phone"><input id="shopUpi" value="'+esc(s.upi)+'" placeholder="UPI ID e.g. shop@upi"><textarea id="shopAddress" placeholder="Shop address">'+esc(s.address)+'</textarea><button class="btn primary" onclick="saveShopSettings()">Save Profile</button>')}
function saveShopSettings(){state.shop={name:(document.getElementById("shopName")?.value||"").trim()||"My Dukaan",owner:(document.getElementById("shopOwner")?.value||"").trim()||"Shop Owner",phone:(document.getElementById("shopPhone")?.value||"").trim(),upi:(document.getElementById("shopUpi")?.value||"").trim(),address:(document.getElementById("shopAddress")?.value||"").trim()};saveState();closeModal();render();toast("Profile saved")}
function openExpenses(){modal('<h2>Record Expense</h2><input id="exName" placeholder="Expense name"><input id="exAmount" type="number" min="0.01" placeholder="Amount"><select id="exMode"><option>cash</option><option>upi</option><option>bank</option><option>card</option></select><button class="btn primary" onclick="saveExpense()">Save Expense</button>')}
function saveExpense(){const n=(document.getElementById("exName")?.value||"").trim(),a=Number(document.getElementById("exAmount")?.value)||0;if(!n||a<=0)return toast("Enter expense details");state.expenses.unshift({id:uid(),name:n,amount:a,mode:document.getElementById("exMode")?.value,date:new Date().toISOString()});saveState();closeModal();render();toast("Expense saved")}
function openReturns(){modal('<h2>Record Return</h2><input id="retName" placeholder="Item / customer"><input id="retAmount" type="number" min="0.01" placeholder="Return amount"><button class="btn primary" onclick="saveReturn()">Save Return</button>')}
function saveReturn(){const n=(document.getElementById("retName")?.value||"").trim(),a=Number(document.getElementById("retAmount")?.value)||0;if(!n||a<=0)return toast("Enter return details");state.returns.unshift({id:uid(),name:n,amount:a,date:new Date().toISOString()});saveState();closeModal();render();toast("Return recorded")}
function openBackup(){modal('<h2>Backup & Restore</h2><p>Your data is stored on this device/browser.</p><button class="btn" onclick="exportData()">⇩ Download backup</button><label class="btn" style="display:block;text-align:center;margin-top:8px">⇧ Restore backup<input type="file" accept=".json,application/json" onchange="importData(event)" hidden></label>')}
function exportData(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="dukaan-khata-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("Backup downloaded")}
function importData(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);localStorage.setItem(KEY,JSON.stringify(x));state=loadState();closeModal();render();toast("Backup restored")}catch(err){toast("Invalid backup file")}};r.readAsText(f)}
function openLanguage(){modal('<h2>Language</h2><button class="btn" onclick="setLanguage(\'English\')">English</button><button class="btn" onclick="setLanguage(\'Hindi\')">हिन्दी</button><button class="btn" onclick="setLanguage(\'Telugu\')">తెలుగు</button>')}
function voiceEntry(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast("Voice input is not supported in this browser");const r=new R();r.lang=state.settings.language==="Telugu"?"te-IN":state.settings.language==="Hindi"?"hi-IN":"en-IN";r.onresult=e=>toast("Heard: "+e.results[0][0].transcript);r.start()}
function openAbout(){modal('<h2>✦ Dukaan Khata Infinity</h2><p>Simple digital tools for Indian shops.</p><div class="line"><span>Digital Khata</span><b>✓</b></div><div class="line"><span>Many items with individual prices</span><b>✓</b></div><div class="line"><span>UPI QR Receive</span><b>✓</b></div><div class="line"><span>Customer Connect</span><b>✓</b></div><div class="line"><span>Backup & Restore</span><b>✓</b></div>')}
function toggleTheme(){state.settings.theme=document.body.classList.contains("darkmode")?"light":"dark";saveState();render()}
function clearDemo(){if(confirm("Clear all Dukaan Khata data on this device?")){localStorage.removeItem(KEY);state=defaults();render();toast("Data reset")}}

function renderKhata(){const box=document.getElementById("khataList");if(!box)return;const q=(document.getElementById("khataSearch")?.value||"").toLowerCase();box.innerHTML=state.customers.filter(c=>{const b=balance(c.id);return(c.name+" "+c.phone).toLowerCase().includes(q)&&(khataFilter==="all"||(khataFilter==="due"&&b>0)||(khataFilter==="paid"&&b<=0))}).map(c=>'<div class="customer" data-long-delete data-delete-type="customer" data-delete-id="'+esc(c.id)+'"><div onclick="customerView(\''+esc(c.id)+'\')" style="flex:1;cursor:pointer"><h3>'+esc(c.name)+'</h3><small>'+esc(c.phone||"No phone added")+'</small></div><div style="text-align:right"><div class="'+(balance(c.id)>0?"due":"paid")+'">'+money(balance(c.id))+'</div>'+(!c.phone?'<button class="btn small" onclick="event.stopPropagation();addCustomerNumber(\''+esc(c.id)+'\')">＋ Add Mobile</button>':"")+'</div></div>').join("")||'<p class="muted">No customers found.</p>'}
function renderCustomers(){const box=document.getElementById("customerList");if(!box)return;const q=(document.getElementById("customerSearch")?.value||"").toLowerCase();box.innerHTML=state.customers.filter(c=>(c.name+" "+c.phone).toLowerCase().includes(q)).map(c=>'<div class="customer" data-long-delete data-delete-type="customer" data-delete-id="'+esc(c.id)+'" onclick="customerView(\''+esc(c.id)+'\')"><div><h3>'+esc(c.name)+'</h3><small>'+esc(c.phone||"No phone")+'</small></div><div class="'+(balance(c.id)>0?"due":"paid")+'">'+money(balance(c.id))+'</div></div>').join("")||'<p class="muted">No customers yet.</p>';const due=state.customers.filter(c=>balance(c.id)>0).length;document.getElementById("customerDueCount")&&(document.getElementById("customerDueCount").textContent=due);document.getElementById("customerPaidCount")&&(document.getElementById("customerPaidCount").textContent=state.customers.length-due)}
function renderBills(){const box=document.getElementById("billList");if(!box)return;box.innerHTML=sales().slice(0,50).map(t=>{const c=state.customers.find(x=>x.id===t.customerId);return'<div class="bill" data-long-delete data-delete-type="sale" data-delete-id="'+esc(t.id)+'" onclick="billView(\''+esc(t.id)+'\')"><div><h3>'+esc(c?.name||"Walk-in")+'</h3><small>'+new Date(t.date).toLocaleString("en-IN")+'</small></div><b>'+money(t.total)+'</b></div>'}).join("")||'<p class="muted">No bills yet.</p>'}
function billView(id){const t=state.tx.find(x=>x.id===id);if(!t)return;const c=state.customers.find(x=>x.id===t.customerId);const lines=(t.lines||[]).map(l=>'<div class="line"><span>'+esc(l.name)+' × '+l.qty+'</span><b>'+money(l.total)+'</b></div>').join("");modal('<h2>Bill</h2><p><b>'+esc(c?.name||"Walk-in")+'</b><br><small>'+new Date(t.date).toLocaleString("en-IN")+'</small></p>'+lines+'<div class="line"><b>Total</b><b>'+money(t.total)+'</b></div><button class="btn" style="background:#dc2626" onclick="deleteSale(\''+esc(id)+'\')">Delete Bill</button>')}
function deleteSale(id){if(!state.tx.some(t=>t.id===id))return;if(!confirm("Delete this bill?"))return;state.tx=state.tx.filter(t=>t.id!==id);saveState();closeModal();render();toast("Bill deleted")}
function deleteTransaction(id){
  const t=state.tx.find(x=>x.id===id);if(!t)return;
  const label=t.type==="sale"?"sale/bill":"payment";
  if(!confirm("Delete this "+label+" transaction?"))return;
  state.tx=state.tx.filter(x=>x.id!==id);saveState();closeModal();render();toast("Transaction deleted")
}
function filterKhata(f,el){khataFilter=f;document.querySelectorAll(".segmented button").forEach(x=>x.classList.remove("active"));el?.classList.add("active");renderKhata()}

function renderReports(){const chart=document.getElementById("activityChart");if(chart){const days=[];for(let n=6;n>=0;n--){const d=new Date();d.setDate(d.getDate()-n);days.push({d,v:sales().filter(t=>new Date(t.date).toDateString()===d.toDateString()).reduce((a,t)=>a+(Number(t.total)||0),0)})}const max=Math.max(1,...days.map(x=>x.v));chart.innerHTML=days.map(x=>'<div class="bar" style="height:'+Math.max(7,x.v/max*125)+'px"><small>'+x.d.toLocaleDateString("en-IN",{weekday:"short"})+'</small></div>').join("")}const top=document.getElementById("topCustomers");if(top)top.innerHTML=state.customers.map(c=>({c,v:balance(c.id)})).sort((a,b)=>b.v-a.v).slice(0,5).map(x=>'<div class="line"><span>'+esc(x.c.name)+'</span><b class="'+(x.v>0?"due":"paid")+'">'+money(x.v)+'</b></div>').join("")||'<p class="muted">No customers yet.</p>'}
function render(){const now=new Date(),today=now.toDateString(),tod=state.tx.filter(t=>new Date(t.date).toDateString()===today);const revenue=sales().reduce((a,t)=>a+(Number(t.total)||0),0),received=payments().reduce((a,t)=>a+(Number(t.amount)||0),0),due=state.customers.reduce((a,c)=>a+Math.max(0,balance(c.id)),0),expenses=state.expenses.reduce((a,t)=>a+(Number(t.amount)||0),0);const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set("ownerHeader",state.shop.name+" • Infinity");set("greeting",(now.getHours()<12?"Good morning":now.getHours()<17?"Good afternoon":"Good evening")+" 👋");set("todayLabel",now.toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long"}));set("totalDue",money(due));set("todaySales",money(tod.filter(t=>t.type==="sale").reduce((a,t)=>a+(Number(t.total)||0),0)));set("todaySalesCount",tod.filter(t=>t.type==="sale").length+" bills");set("todayPaid",money(tod.filter(t=>t.type==="payment").reduce((a,t)=>a+(Number(t.amount)||0),0)));set("customerCount",state.customers.length);set("newCustomers",state.customers.length+" active");set("overdueCount",state.customers.filter(c=>balance(c.id)>0).length+" with due");set("collectionRate",revenue?Math.round(received/revenue*100)+"% collected":"0% collected");set("rRevenue",money(revenue));set("rCredit",money(Math.max(0,revenue-received)));set("rPaid",money(received));set("rExpense",money(expenses));set("rTx",state.tx.length);const rec=document.getElementById("recent");if(rec)rec.innerHTML=state.tx.slice(0,6).map(t=>'<div class="activity" data-long-delete data-delete-type="transaction" data-delete-id="'+esc(t.id)+'"><div style="display:flex;justify-content:space-between"><span>'+(t.type==="sale"?"🧾":"💰")+' '+esc(state.customers.find(c=>c.id===t.customerId)?.name||"Customer")+'</span><b>'+money(t.type==="sale"?t.total:t.amount)+'</b></div><small class="muted">'+(t.type==="sale"?"Sale":"Payment")+' • Long press to delete</small></div>').join("")||'<p class="muted">No activity yet.</p>';renderKhata();renderCustomers();renderBills();renderReports();document.body.classList.toggle("darkmode",state.settings.theme==="dark");if(window.applyLanguage)setTimeout(window.applyLanguage,0)}

function setupLongPress(){
  document.addEventListener("pointerdown",e=>{
    const el=e.target.closest?.("[data-long-delete]");if(!el)return;
    longPress={el,fired:false,t:setTimeout(()=>{
      longPress.fired=true;el.classList.add("long-press-delete");
      if(el.dataset.deleteType==="customer")deleteCustomer(el.dataset.deleteId);
      else if(el.dataset.deleteType==="sale")deleteSale(el.dataset.deleteId);
      else if(el.dataset.deleteType==="transaction")deleteTransaction(el.dataset.deleteId);
    },750)}
  });
  document.addEventListener("pointerup",e=>{
    if(longPress){clearTimeout(longPress.t);if(longPress.fired)e.preventDefault();longPress.el?.classList.remove("long-press-delete");longPress=null}
  });
  document.addEventListener("pointercancel",()=>{if(longPress){clearTimeout(longPress.t);longPress.el?.classList.remove("long-press-delete");longPress=null}});
  document.addEventListener("click",e=>{
    if(e.target.closest?.("[data-long-delete]") && longPress?.fired)e.preventDefault();
  },true);
}
document.addEventListener("DOMContentLoaded",()=>{setupLongPress();render()});
