/* Dukaan Khata Infinity multilingual UI */
(function(){
  const T={
    English:{greeting:"Good morning 👋",glance:"Your shop at a glance",outstanding:"Outstanding to receive",overdue:"overdue",collected:"collected",sales:"Sales today",received:"Received today",customers:"Customers",lowstock:"Low stock",bills:"bills",methods:"All methods",active:"active",attention:"Needs attention",viewall:"View all",recent:"Recent activity",reports:"Reports",ledger:"LEDGER",khata:"Khata",all:"All",due:"Due",paid:"Paid",people:"PEOPLE",add:"Add",stock:"STOCK",items:"Items",stockvalue:"Stock value",billing:"BILLING",billssales:"Bills & Sales",backup:"Backup",expenses:"Expenses",returns:"Returns",insights:"INSIGHTS",businessvalue:"Business value",allsales:"All recorded sales",creditsales:"Credit sales",transactions:"Transactions",activity:"7-day activity",topcustomers:"Top customers",tools:"TOOLS",more:"More",smartrcv:"Smart Receive",connect:"Customer Connect",reminder:"Reminder Center",digitalpass:"Digital Shop Pass",shopprofile:"Shop profile",voice:"Voice entry",about:"Dukaan Khata Pro",reset:"Reset demo",home:"Home",billsnav:"Bills",stocknav:"Stock",customer:"Customer",inventory:"Inventory",newSale:"New Sale",receive:"Receive",hub:"Customer Hub",language:"Language",restock:"Restock",clear:"All clear 🎉",noactivity:"No activity yet. Start with New Sale.",searchCustomer:"⌕ Search customer...",namephone:"⌕ Name or phone...",searchItem:"⌕ Search item...",languageSet:"Language set to "},
    Hindi:{greeting:"सुप्रभात 👋",glance:"आपकी दुकान की एक झलक",outstanding:"प्राप्त करना बाकी",overdue:"बकाया",collected:"प्राप्त",sales:"आज की बिक्री",received:"आज प्राप्त",customers:"ग्राहक",lowstock:"कम स्टॉक",bills:"बिल",methods:"सभी तरीके",active:"सक्रिय",attention:"ध्यान देने की जरूरत",viewall:"सब देखें",recent:"हाल की गतिविधि",reports:"रिपोर्ट",ledger:"खाता",khata:"खाता",all:"सभी",due:"बकाया",paid:"भुगतान",people:"ग्राहक",add:"जोड़ें",stock:"स्टॉक",items:"आइटम",stockvalue:"स्टॉक मूल्य",billing:"बिलिंग",billssales:"बिल और बिक्री",backup:"बैकअप",expenses:"खर्च",returns:"रिटर्न",insights:"जानकारी",businessvalue:"व्यापार मूल्य",allsales:"सभी दर्ज बिक्री",creditsales:"उधार बिक्री",transactions:"लेन-देन",activity:"7 दिन की गतिविधि",topcustomers:"शीर्ष ग्राहक",tools:"टूल्स",more:"और",smartrcv:"स्मार्ट भुगतान प्राप्ति",connect:"ग्राहक संपर्क",reminder:"रिमाइंडर केंद्र",digitalpass:"डिजिटल दुकान पास",shopprofile:"दुकान प्रोफ़ाइल",voice:"आवाज़ से एंट्री",about:"दुकान खाता प्रो",reset:"डेमो रीसेट",home:"होम",billsnav:"बिल",stocknav:"स्टॉक",customer:"ग्राहक",inventory:"इन्वेंटरी",newSale:"नई बिक्री",receive:"प्राप्त करें",hub:"ग्राहक केंद्र",language:"भाषा",restock:"स्टॉक भरें",clear:"सब ठीक है 🎉",noactivity:"अभी कोई गतिविधि नहीं। नई बिक्री से शुरू करें।",searchCustomer:"⌕ ग्राहक खोजें...",namephone:"⌕ नाम या फोन...",searchItem:"⌕ आइटम खोजें...",languageSet:"भाषा चुनी गई: "},
    Telugu:{greeting:"శుభోదయం 👋",glance:"మీ షాప్ ఒక చూపులో",outstanding:"అందుకోవాల్సిన మొత్తం",overdue:"బకాయి",collected:"వసూలైంది",sales:"ఈరోజు అమ్మకాలు",received:"ఈరోజు అందుకున్నది",customers:"కస్టమర్లు",lowstock:"తక్కువ స్టాక్",bills:"బిల్లులు",methods:"అన్ని పద్ధతులు",active:"యాక్టివ్",attention:"శ్రద్ధ అవసరం",viewall:"అన్నీ చూడండి",recent:"ఇటీవలి కార్యకలాపాలు",reports:"రిపోర్టులు",ledger:"ఖాతా",khata:"ఖాతా",all:"అన్నీ",due:"బకాయి",paid:"చెల్లింపు",people:"కస్టమర్లు",add:"జోడించు",stock:"స్టాక్",items:"ఐటమ్స్",stockvalue:"స్టాక్ విలువ",billing:"బిల్లింగ్",billssales:"బిల్లులు & అమ్మకాలు",backup:"బ్యాకప్",expenses:"ఖర్చులు",returns:"రిటర్న్స్",insights:"సమాచారం",businessvalue:"వ్యాపార విలువ",allsales:"నమోదైన అన్ని అమ్మకాలు",creditsales:"క్రెడిట్ అమ్మకాలు",transactions:"లావాదేవీలు",activity:"7 రోజుల కార్యకలాపాలు",topcustomers:"ముఖ్య కస్టమర్లు",tools:"టూల్స్",more:"మరిన్ని",smartrcv:"స్మార్ట్ రిసీవ్",connect:"కస్టమర్ కనెక్ట్",reminder:"రిమైండర్ సెంటర్",digitalpass:"డిజిటల్ షాప్ పాస్",shopprofile:"షాప్ ప్రొఫైల్",voice:"వాయిస్ ఎంట్రీ",about:"దుకాణ ఖాతా ప్రో",reset:"డెమో రీసెట్",home:"హోమ్",billsnav:"బిల్లులు",stocknav:"స్టాక్",customer:"కస్టమర్",inventory:"ఇన్వెంటరీ",newSale:"కొత్త అమ్మకం",receive:"స్వీకరించండి",hub:"కస్టమర్ హబ్",language:"భాష",restock:"స్టాక్ నింపండి",clear:"అన్నీ బాగున్నాయి 🎉",noactivity:"ఇంకా కార్యకలాపాలు లేవు. కొత్త అమ్మకంతో ప్రారంభించండి.",searchCustomer:"⌕ కస్టమర్‌ను వెతకండి...",namephone:"⌕ పేరు లేదా ఫోన్...",searchItem:"⌕ ఐటమ్‌ను వెతకండి...",languageSet:"భాష ఎంచుకోబడింది: "}
  };
  function lang(){return (window.state&&state.settings&&state.settings.language)||localStorage.getItem("dukaan_khata_language")||"English"}
  function setText(sel,key){const e=document.querySelector(sel);if(e&&T[lang()][key])e.textContent=T[lang()][key]}
  function setHTML(sel,key){const e=document.querySelector(sel);if(e&&T[lang()][key])e.innerHTML=T[lang()][key]}
  window.applyLanguage=function(){
    const L=T[lang()]||T.English;
    document.documentElement.lang=lang()==="Hindi"?"hi":lang()==="Telugu"?"te":"en";
    setText("#greeting","greeting");setText(".welcome h2","glance");setText(".balance-hero span","outstanding");
    document.querySelectorAll(".stat").forEach((e,i)=>{const k=["sales","received","customers","lowstock"][i];if(L[k])e.querySelector("span").textContent=L[k]});
    const salesSmall=document.querySelector("#todayPaid")?.parentElement?.querySelector("small");if(salesSmall)salesSmall.textContent=L.methods;
    document.querySelectorAll(".section-head h3").forEach((e,i)=>e.textContent=i?L.recent:L.attention);
    document.querySelectorAll(".section-head .text-link").forEach((e,i)=>e.textContent=i?L.reports:L.viewall);
    const pageMap=[["khata","ledger","khata"],["customers","people","customers"],["inventory","stock","inventory"],["bills","billing","billssales"],["reports","insights","reports"],["tools","tools","more"]];
    pageMap.forEach(([id,ey,h])=>{const p=document.getElementById(id);if(p){const x=p.querySelector(".eyebrow");const y=p.querySelector(".page-title h2");if(x)x.textContent=L[ey];if(y)y.textContent=L[h]}});
    const kh=document.querySelectorAll("#khata .segmented button");["all","due","paid"].forEach((k,i)=>{if(kh[i])kh[i].textContent=L[k]});
    document.querySelector("#khataSearch")?.setAttribute("placeholder",L.searchCustomer);
    document.querySelector("#customerSearch")?.setAttribute("placeholder",L.namephone);
    document.querySelector("#itemSearch")?.setAttribute("placeholder",L.searchItem);
    const inv=document.querySelectorAll("#inventory .inventory-cards span");["items","stockvalue","lowstock"].forEach((k,i)=>{if(inv[i])inv[i].textContent=L[k]});
    const repHero=document.querySelector(".report-hero");if(repHero){repHero.querySelector("span").textContent=L.businessvalue;repHero.querySelector("small").textContent=L.allsales}
    const rg=document.querySelectorAll(".report-grid span");["creditsales","received","expenses","transactions"].forEach((k,i)=>{if(rg[i])rg[i].textContent=L[k]});
    const cards=document.querySelectorAll("#reports .card h3");if(cards[0])cards[0].textContent=L.activity;if(cards[1])cards[1].textContent=L.topcustomers;
    const q=document.querySelectorAll(".quick span");["newSale","receive","customer","inventory","hub"].forEach((k,i)=>{if(q[i])q[i].textContent=L[k]});
    const nav=document.querySelectorAll(".bottom-nav span");[L.home,L.khata,L.stocknav,L.billsnav,L.more].forEach((v,i)=>{if(nav[i])nav[i].textContent=v});
    const tools=document.querySelectorAll(".tools-grid button b");["smartrcv","connect","reminder","digitalpass","shopprofile","expenses","returns","backup","language","voice","about","reset"].forEach((k,i)=>{if(tools[i])tools[i].textContent=L[k]});
    const toolSmall=document.querySelectorAll(".tools-grid button small");const sm=["UPI QR + payment links","WhatsApp + calls + reminders","Due follow-ups","Share your shop identity","Name, phone, address","Track shop spending","Record returns","Protect your data","English / Hindi / Telugu","Speak a note or customer","Smart shop toolkit","Clear local data"];if(lang()==="Hindi"){sm[0]="UPI QR + भुगतान लिंक";sm[1]="WhatsApp + कॉल + रिमाइंडर";sm[2]="बकाया फॉलो-अप";sm[3]="दुकान की पहचान शेयर करें";sm[4]="नाम, फोन, पता";sm[5]="दुकान का खर्च ट्रैक करें";sm[6]="रिटर्न दर्ज करें";sm[7]="अपना डेटा सुरक्षित रखें";sm[8]="अंग्रेज़ी / हिंदी / तेलुगु";sm[9]="नोट या ग्राहक बोलें";sm[10]="स्मार्ट दुकान टूलकिट";sm[11]="लोकल डेटा साफ करें"}else if(lang()==="Telugu"){sm[0]="UPI QR + చెల్లింపు లింకులు";sm[1]="WhatsApp + కాల్స్ + రిమైండర్లు";sm[2]="బకాయి ఫాలో-అప్స్";sm[3]="షాప్ వివరాలు షేర్ చేయండి";sm[4]="పేరు, ఫోన్, చిరునామా";sm[5]="షాప్ ఖర్చులు ట్రాక్ చేయండి";sm[6]="రిటర్న్స్ నమోదు";sm[7]="డేటాను సురక్షితంగా ఉంచండి";sm[8]="ఇంగ్లీష్ / హిందీ / తెలుగు";sm[9]="నోట్ లేదా కస్టమర్ మాట్లాడండి";sm[10]="స్మార్ట్ షాప్ టూల్‌కిట్";sm[11]="లోకల్ డేటా క్లియర్ చేయండి"}toolSmall.forEach((e,i)=>{if(sm[i])e.textContent=sm[i]});
    const languageBtn=document.querySelector('.tools-grid button[onclick="openLanguage()"] small');if(languageBtn)languageBtn.textContent=lang();
  };
  window.setLanguage=function(x){
    if(window.state&&state.settings){state.settings.language=x;if(typeof saveState==="function")saveState()}
    localStorage.setItem("dukaan_khata_language",x);
    applyLanguage();
    if(typeof closeModal==="function")closeModal();
    const L=T[x]||T.English;
    if(typeof toast==="function")toast(L.languageSet+x);
  };
  window.openLanguage=function(){
    const L=T[lang()]||T.English;
    if(typeof modal==="function")modal("<h2>"+L.language+"</h2><button class='btn' onclick=\"setLanguage('English')\">English</button><button class='btn' onclick=\"setLanguage('Hindi')\">हिन्दी</button><button class='btn' onclick=\"setLanguage('Telugu')\">తెలుగు</button>");
  };
  document.addEventListener("DOMContentLoaded",function(){setTimeout(applyLanguage,30)});
})();
