/* Dukaan Khata — Indian language support */
(function(){
  const T={
    English:{greeting:"Good morning 👋",glance:"Your shop at a glance",outstanding:"Outstanding to receive",sales:"Sales today",received:"Received today",customers:"Customers",recent:"Recent activity",reports:"Reports",khata:"Khata",all:"All",due:"Due",paid:"Paid",people:"Customers",billssales:"Bills & Sales",more:"More",smartrcv:"Smart Receive",shopprofile:"Shop Profile",language:"Language",connect:"Customer Contact",login:"Login Access",digitalpass:"Digital App Pass",home:"Home",billsnav:"Bills",customer:"Customers",languageSet:"Language set to "},
    Telugu:{greeting:"శుభోదయం 👋",glance:"మీ షాప్ ఒక చూపులో",outstanding:"అందుకోవాల్సిన మొత్తం",sales:"ఈరోజు అమ్మకాలు",received:"ఈరోజు అందుకున్నది",customers:"కస్టమర్లు",recent:"ఇటీవలి కార్యకలాపాలు",reports:"రిపోర్టులు",khata:"ఖాతా",all:"అన్నీ",due:"బకాయి",paid:"చెల్లింపు",people:"కస్టమర్లు",billssales:"బిల్లులు & అమ్మకాలు",more:"మరిన్ని",smartrcv:"స్మార్ట్ రిసీవ్",shopprofile:"షాప్ ప్రొఫైల్",language:"భాష",connect:"కస్టమర్ సంప్రదింపు",login:"లాగిన్ యాక్సెస్",digitalpass:"డిజిటల్ యాప్ పాస్",home:"హోమ్",billsnav:"బిల్లులు",customer:"కస్టమర్లు",languageSet:"భాష ఎంచుకోబడింది: "},
    Hindi:{greeting:"सुप्रभात 👋",glance:"आपकी दुकान की एक झलक",outstanding:"प्राप्त करना बाकी",sales:"आज की बिक्री",received:"आज प्राप्त",customers:"ग्राहक",recent:"हाल की गतिविधि",reports:"रिपोर्ट",khata:"खाता",all:"सभी",due:"बकाया",paid:"भुगतान",people:"ग्राहक",billssales:"बिल और बिक्री",more:"और",smartrcv:"स्मार्ट रिसीव",shopprofile:"दुकान प्रोफ़ाइल",language:"भाषा",connect:"ग्राहक संपर्क",login:"लॉगिन एक्सेस",digitalpass:"डिजिटल ऐप पास",home:"होम",billsnav:"बिल",customer:"ग्राहक",languageSet:"भाषा चुनी गई: "},
    Kannada:{greeting:"ಶುಭೋದಯ 👋",glance:"ನಿಮ್ಮ ಅಂಗಡಿಯ ಒಂದು ನೋಟ",outstanding:"ಪಡೆಯಬೇಕಾದ ಮೊತ್ತ",sales:"ಇಂದಿನ ಮಾರಾಟ",received:"ಇಂದು ಪಡೆದದ್ದು",customers:"ಗ್ರಾಹಕರು",recent:"ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",reports:"ವರದಿಗಳು",khata:"ಖಾತೆ",all:"ಎಲ್ಲಾ",due:"ಬಾಕಿ",paid:"ಪಾವತಿಸಲಾಗಿದೆ",people:"ಗ್ರಾಹಕರು",billssales:"ಬಿಲ್‌ಗಳು ಮತ್ತು ಮಾರಾಟ",more:"ಇನ್ನಷ್ಟು",smartrcv:"ಸ್ಮಾರ್ಟ್ ರಿಸೀವ್",shopprofile:"ಅಂಗಡಿ ಪ್ರೊಫೈಲ್",language:"ಭಾಷೆ",connect:"ಗ್ರಾಹಕ ಸಂಪರ್ಕ",login:"ಲಾಗಿನ್ ಪ್ರವೇಶ",digitalpass:"ಡಿಜಿಟಲ್ ಆಪ್ ಪಾಸ್",home:"ಹೋಮ್",billsnav:"ಬಿಲ್‌ಗಳು",customer:"ಗ್ರಾಹಕರು",languageSet:"ಭಾಷೆ ಆಯ್ಕೆ: "},
    Marathi:{greeting:"सुप्रभात 👋",glance:"तुमच्या दुकानाची एक झलक",outstanding:"घेणे बाकी",sales:"आजची विक्री",received:"आज प्राप्त",customers:"ग्राहक",recent:"अलीकडील क्रियाकलाप",reports:"अहवाल",khata:"खाते",all:"सर्व",due:"बाकी",paid:"भरले",people:"ग्राहक",billssales:"बिले आणि विक्री",more:"अधिक",smartrcv:"स्मार्ट रिसीव्ह",shopprofile:"दुकान प्रोफाइल",language:"भाषा",connect:"ग्राहक संपर्क",login:"लॉगिन प्रवेश",digitalpass:"डिजिटल अॅप पास",home:"होम",billsnav:"बिले",customer:"ग्राहक",languageSet:"भाषा निवडली: "},
    Bengali:{greeting:"সুপ্রভাত 👋",glance:"আপনার দোকানের এক ঝলক",outstanding:"পাওনা",sales:"আজকের বিক্রি",received:"আজ প্রাপ্ত",customers:"গ্রাহক",recent:"সাম্প্রতিক কার্যকলাপ",reports:"রিপোর্ট",khata:"খাতা",all:"সব",due:"বাকি",paid:"পরিশোধিত",people:"গ্রাহক",billssales:"বিল ও বিক্রি",more:"আরও",smartrcv:"স্মার্ট রিসিভ",shopprofile:"দোকানের প্রোফাইল",language:"ভাষা",connect:"গ্রাহক যোগাযোগ",login:"লগইন অ্যাক্সেস",digitalpass:"ডিজিটাল অ্যাপ পাস",home:"হোম",billsnav:"বিল",customer:"গ্রাহক",languageSet:"ভাষা নির্বাচিত: "},
    Assamese:{greeting:"সুপ্ৰভাত 👋",glance:"আপোনাৰ দোকানৰ এক আভাস",outstanding:"পাবলগীয়া ধন",sales:"আজিৰ বিক্ৰী",received:"আজি পোৱা ধন",customers:"গ্ৰাহক",recent:"শেহতীয়া কাৰ্যকলাপ",reports:"প্ৰতিবেদন",khata:"খাতা",all:"সকলো",due:"বাকী",paid:"পৰিশোধিত",people:"গ্ৰাহক",billssales:"বিল আৰু বিক্ৰী",more:"অধিক",smartrcv:"স্মাৰ্ট ৰিচিভ",shopprofile:"দোকানৰ প্ৰফাইল",language:"ভাষা",connect:"গ্ৰাহক যোগাযোগ",login:"লগইন",digitalpass:"ডিজিটেল এপ পাছ",home:"হোম",billsnav:"বিল",customer:"গ্ৰাহক",languageSet:"ভাষা নিৰ্বাচিত: "},
    Gujarati:{greeting:"સુપ્રભાત 👋",glance:"તમારી દુકાનની એક ઝલક",outstanding:"લેવાના બાકી",sales:"આજનું વેચાણ",received:"આજે મળેલ",customers:"ગ્રાહકો",recent:"તાજેતરની પ્રવૃત્તિ",reports:"અહેવાલ",khata:"ખાતું",all:"બધા",due:"બાકી",paid:"ચૂકવેલ",people:"ગ્રાહકો",billssales:"બિલ અને વેચાણ",more:"વધુ",smartrcv:"સ્માર્ટ રિસીવ",shopprofile:"દુકાન પ્રોફાઇલ",language:"ભાષા",connect:"ગ્રાહક સંપર્ક",login:"લોગિન ઍક્સેસ",digitalpass:"ડિજિટલ એપ પાસ",home:"હોમ",billsnav:"બિલ",customer:"ગ્રાહક",languageSet:"ભાષા પસંદ: "},
    Malayalam:{greeting:"സുപ്രഭാതം 👋",glance:"നിങ്ങളുടെ കടയുടെ ഒരു നോട്ടം",outstanding:"ലഭിക്കാനുള്ളത്",sales:"ഇന്നത്തെ വിൽപ്പന",received:"ഇന്ന് ലഭിച്ചത്",customers:"ഉപഭോക്താക്കൾ",recent:"സമീപകാല പ്രവർത്തനം",reports:"റിപ്പോർട്ടുകൾ",khata:"ഖാത്ത",all:"എല്ലാം",due:"ബാക്കി",paid:"അടച്ചത്",people:"ഉപഭോക്താക്കൾ",billssales:"ബില്ലുകളും വിൽപ്പനയും",more:"കൂടുതൽ",smartrcv:"സ്മാർട്ട് റിസീവ്",shopprofile:"കട പ്രൊഫൈൽ",language:"ഭാഷ",connect:"ഉപഭോക്തൃ ബന്ധം",login:"ലോഗിൻ ആക്സസ്",digitalpass:"ഡിജിറ്റൽ ആപ്പ് പാസ്",home:"ഹോം",billsnav:"ബില്ലുകൾ",customer:"ഉപഭോക്താവ്",languageSet:"ഭാഷ തിരഞ്ഞെടുത്തു: "},
    Punjabi:{greeting:"ਸਤ ਸ੍ਰੀ ਅਕਾਲ 👋",glance:"ਤੁਹਾਡੀ ਦੁਕਾਨ ਦੀ ਝਲਕ",outstanding:"ਲੈਣ ਵਾਲੀ ਰਕਮ",sales:"ਅੱਜ ਦੀ ਵਿਕਰੀ",received:"ਅੱਜ ਪ੍ਰਾਪਤ",customers:"ਗਾਹਕ",recent:"ਹਾਲੀਆ ਗਤੀਵਿਧੀ",reports:"ਰਿਪੋਰਟਾਂ",khata:"ਖਾਤਾ",all:"ਸਾਰੇ",due:"ਬਕਾਇਆ",paid:"ਅਦਾ ਕੀਤਾ",people:"ਗਾਹਕ",billssales:"ਬਿੱਲ ਅਤੇ ਵਿਕਰੀ",more:"ਹੋਰ",smartrcv:"ਸਮਾਰਟ ਰਿਸੀਵ",shopprofile:"ਦੁਕਾਨ ਪ੍ਰੋਫਾਈਲ",language:"ਭਾਸ਼ਾ",connect:"ਗਾਹਕ ਸੰਪਰਕ",login:"ਲੌਗਇਨ ਐਕਸੈਸ",digitalpass:"ਡਿਜੀਟਲ ਐਪ ਪਾਸ",home:"ਹੋਮ",billsnav:"ਬਿੱਲ",customer:"ਗਾਹਕ",languageSet:"ਭਾਸ਼ਾ ਚੁਣੀ: "},
    Odia:{greeting:"ସୁପ୍ରଭାତ 👋",glance:"ଆପଣଙ୍କ ଦୋକାନର ଏକ ଝଲକ",outstanding:"ପାଇବାକୁ ଥିବା",sales:"ଆଜିର ବିକ୍ରି",received:"ଆଜି ପ୍ରାପ୍ତ",customers:"ଗ୍ରାହକ",recent:"ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ",reports:"ରିପୋର୍ଟ",khata:"ଖାତା",all:"ସମସ୍ତ",due:"ବାକି",paid:"ପୈଠ",people:"ଗ୍ରାହକ",billssales:"ବିଲ୍ ଓ ବିକ୍ରି",more:"ଅଧିକ",smartrcv:"ସ୍ମାର୍ଟ ରିସିଭ୍",shopprofile:"ଦୋକାନ ପ୍ରୋଫାଇଲ୍",language:"ଭାଷା",connect:"ଗ୍ରାହକ ଯୋଗାଯୋଗ",login:"ଲଗଇନ୍ ଆକ୍ସେସ୍",digitalpass:"ଡିଜିଟାଲ୍ ଆପ୍ ପାସ୍",home:"ହୋମ୍",billsnav:"ବିଲ୍",customer:"ଗ୍ରାହକ",languageSet:"ଭାଷା ଚୟନ: "},
    Tamil:{greeting:"காலை வணக்கம் 👋",glance:"உங்கள் கடையின் ஒரு பார்வை",outstanding:"பெற வேண்டியது",sales:"இன்றைய விற்பனை",received:"இன்று பெற்றது",customers:"வாடிக்கையாளர்கள்",recent:"சமீபத்திய செயல்பாடு",reports:"அறிக்கைகள்",khata:"கணக்கு",all:"அனைத்தும்",due:"பாக்கி",paid:"செலுத்தியது",people:"வாடிக்கையாளர்கள்",billssales:"பில்கள் & விற்பனை",more:"மேலும்",smartrcv:"ஸ்மார்ட் ரிசீவ்",shopprofile:"கடை சுயவிவரம்",language:"மொழி",connect:"வாடிக்கையாளர் தொடர்பு",login:"உள்நுழைவு",digitalpass:"டிஜிட்டல் ஆப் பாஸ்",home:"முகப்பு",billsnav:"பில்கள்",customer:"வாடிக்கையாளர்",languageSet:"மொழி தேர்ந்தெடுக்கப்பட்டது: "},
    Urdu:{greeting:"صبح بخیر 👋",glance:"آپ کی دکان کی ایک جھلک",outstanding:"وصول کرنا باقی",sales:"آج کی فروخت",received:"آج وصول شدہ",customers:"گاہک",recent:"حالیہ سرگرمی",reports:"رپورٹس",khata:"کھاتہ",all:"سب",due:"بقایا",paid:"ادا شدہ",people:"گاہک",billssales:"بل اور فروخت",more:"مزید",smartrcv:"اسمارٹ وصول",shopprofile:"دکان پروفائل",language:"زبان",connect:"گاہک رابطہ",login:"لاگ اِن",digitalpass:"ڈیجیٹل ایپ پاس",home:"ہوم",billsnav:"بل",customer:"گاہک",languageSet:"زبان منتخب: "},
    Kashmiri:{greeting:"صبح بخیر 👋",glance:"تُہند دُکان ہُند نظر",outstanding:"وصول کرُن باقی",sales:"آجُک فروخت",received:"آج وصول",customers:"گاہک",recent:"حالیہ سرگرمی",reports:"رپورٹس",khata:"کھاتہ",all:"تمام",due:"بقایا",paid:"ادا",people:"گاہک",billssales:"بل تہ فروخت",more:"مزید",smartrcv:"اسمارٹ وصول",shopprofile:"دکان پروفائل",language:"زبان",connect:"گاہک رابطہ",login:"لاگ اِن",digitalpass:"ڈیجیٹل ایپ پاس",home:"ہوم",billsnav:"بل",customer:"گاہک",languageSet:"زبان منتخب: "},
    Konkani:{greeting:"शुभ प्रभात 👋",glance:"तुमच्या दुकानाची एक झलक",outstanding:"घेणे बाकी",sales:"आजची विक्री",received:"आज मिळाले",customers:"गिऱ्हाईक",recent:"अलीकडील हालचाल",reports:"अहवाल",khata:"खातें",all:"सगळें",due:"उरिल्लें",paid:"फेडलें",people:"गिऱ्हाईक",billssales:"बिलां आनी विक्री",more:"अधिक",smartrcv:"स्मार्ट रिसीव्ह",shopprofile:"दुकान प्रोफाइल",language:"भास",connect:"गिऱ्हाईक संपर्क",login:"लॉगिन प्रवेश",digitalpass:"डिजिटल अॅप पास",home:"मुखपान",billsnav:"बिलां",customer:"गिऱ्हाईक",languageSet:"भास निवडली: "},
    Manipuri:{greeting:"ꯁꯨꯄ꯭ꯔꯕꯥꯠ 👋",glance:"ꯅꯣꯡꯆꯨꯞ ꯀꯤ ꯁꯣꯄꯁꯤꯡ",outstanding:"ꯂꯧꯅꯕ ꯄꯥꯏꯁꯥ",sales:"ꯅꯣꯡꯆꯨꯞ ꯁꯤꯡ",received:"ꯂꯧꯔꯕ",customers:"ꯀꯁꯇꯃꯔ",recent:"ꯍꯧꯖꯤꯛ ꯑꯃꯁꯨꯡ",reports:"ꯔꯤꯄꯣꯔꯠ",khata:"ꯈꯥꯇꯥ",all:"ꯄꯨꯝꯅꯃꯛ",due:"ꯂꯩꯔꯤꯕ",paid:"ꯄꯥꯏꯗ",people:"ꯀꯁꯇꯃꯔ",billssales:"ꯕꯤꯜ ꯑꯃꯁꯨꯡ ꯁꯤꯡ",more:"ꯍꯦꯅꯒꯤ",smartrcv:"ꯏꯁꯃꯥꯔꯠ ꯔꯤꯁꯤꯕ",shopprofile:"ꯁꯣꯞ ꯄ꯭ꯔꯣꯐꯥꯏꯜ",language:"ꯂꯣꯟ",connect:"ꯀꯁꯇꯃꯔ ꯀꯝꯄꯦꯜ",login:"ꯂꯣꯒꯤꯟ",digitalpass:"ꯗꯤꯖꯤꯇꯦꯜ ꯑꯦꯞ ꯄꯥꯁ",home:"ꯍꯣꯝ",billsnav:"ꯕꯤꯜ",customer:"ꯀꯁꯇꯃꯔ",languageSet:"ꯂꯣꯟ ꯈꯜꯂꯦ: "},
    Sanskrit:{greeting:"सुप्रभातम् 👋",glance:"भवतः आपणस्य संक्षिप्तदृश्यं",outstanding:"प्रापणीयम्",sales:"अद्य विक्रयः",received:"अद्य प्राप्तम्",customers:"ग्राहकाः",recent:"अद्यतनक्रिया",reports:"प्रतिवेदनानि",khata:"खाता",all:"सर्वम्",due:"देयम्",paid:"दत्तम्",people:"ग्राहकाः",billssales:"बिलानि च विक्रयश्च",more:"अधिकम्",smartrcv:"स्मार्ट प्राप्ति",shopprofile:"आपण-परिचयः",language:"भाषा",connect:"ग्राहकसम्पर्कः",login:"प्रवेशः",digitalpass:"डिजिटल आप्-पास्",home:"गृहम्",billsnav:"बिलानि",customer:"ग्राहकः",languageSet:"भाषा चयनम्: "},
    Maithili:{greeting:"सुप्रभात 👋",glance:"अहाँक दोकानक एक झलक",outstanding:"पाबै के बाकी",sales:"आइक बिक्री",received:"आइ प्राप्त",customers:"ग्राहक",recent:"हालक गतिविधि",reports:"रिपोर्ट",khata:"खाता",all:"सभ",due:"बाकी",paid:"भुगतान भेल",people:"ग्राहक",billssales:"बिल आ बिक्री",more:"बेसी",smartrcv:"स्मार्ट रिसीव",shopprofile:"दोकान प्रोफाइल",language:"भाषा",connect:"ग्राहक सम्पर्क",login:"लॉगिन",digitalpass:"डिजिटल एप पास",home:"होम",billsnav:"बिल",customer:"ग्राहक",languageSet:"भाषा चुनल गेल: "},
    Nepali:{greeting:"शुभ प्रभात 👋",glance:"तपाईंको पसलको झलक",outstanding:"लिन बाँकी",sales:"आजको बिक्री",received:"आज प्राप्त",customers:"ग्राहक",recent:"हालैको गतिविधि",reports:"रिपोर्टहरू",khata:"खाता",all:"सबै",due:"बाँकी",paid:"भुक्तानी",people:"ग्राहक",billssales:"बिल र बिक्री",more:"थप",smartrcv:"स्मार्ट रिसिभ",shopprofile:"पसल प्रोफाइल",language:"भाषा",connect:"ग्राहक सम्पर्क",login:"लगइन पहुँच",digitalpass:"डिजिटल एप पास",home:"गृह",billsnav:"बिल",customer:"ग्राहक",languageSet:"भाषा चयन: "},
    Sindhi:{greeting:"صبح بخير 👋",glance:"توهان جي دڪان جي جھلڪ",outstanding:"وصول ڪرڻو",sales:"اڄ جي وڪري",received:"اڄ وصول ٿيل",customers:"گراهڪ",recent:"تازو سرگرمي",reports:"رپورٽون",khata:"کاتو",all:"سڀ",due:"بقايا",paid:"ادا ٿيل",people:"گراهڪ",billssales:"بل ۽ وڪرو",more:"وڌيڪ",smartrcv:"سمارٽ وصول",shopprofile:"دڪان پروفائل",language:"ٻولي",connect:"گراهڪ رابطو",login:"لاگ اِن",digitalpass:"ڊجيٽل ايپ پاس",home:"گهر",billsnav:"بل",customer:"گراهڪ",languageSet:"ٻولي چونڊي وئي: "},
    Dogri:{greeting:"सुप्रभात 👋",glance:"तुआढ़ी दुकान दा इक झलक",outstanding:"लैणा बाकी",sales:"अज्ज दी बिक्री",received:"अज्ज प्राप्त",customers:"ग्राहक",recent:"हाल दी गतिविधि",reports:"रिपोर्टां",khata:"खाता",all:"सारे",due:"बाकी",paid:"अदा",people:"ग्राहक",billssales:"बिल ते बिक्री",more:"होर",smartrcv:"स्मार्ट रिसीव",shopprofile:"दुकान प्रोफाइल",language:"भाशा",connect:"ग्राहक संपर्क",login:"लॉगिन",digitalpass:"डिजिटल ऐप पास",home:"घर",billsnav:"बिल",customer:"ग्राहक",languageSet:"भाशा चुनी: "},
    Bodo:{greeting:"सुबुं फुं 👋",glance:"नोंनि दुकाननि मोनसे नुथाय",outstanding:"लाफानाय थाखाय",sales:"दिनैनि साय",received:"दिनै लाबाय",customers:"खौरां",recent:"दानि खामानि",reports:"रिपर्ट",khata:"खाता",all:"गासै",due:"बाकि",paid:"फैसाब",people:"खौरां",billssales:"बिल आरो साय",more:"बांसिन",smartrcv:"स्मार्ट रिसिभ",shopprofile:"दुकान प्रोफाइल",language:"राव",connect:"खौरां सोमोन्दो",login:"लोगिन",digitalpass:"डिजिटल एप पास",home:"न'",billsnav:"बिल",customer:"खौरां",languageSet:"राव सायखना: "},
    Santali:{greeting:"ᱥᱩᱵᱷ ᱵᱤᱦᱟᱱ 👋",glance:"ᱟᱢᱟᱜ ᱫᱩᱠᱟᱱ ᱨᱮ ᱧᱮᱞ",outstanding:"ᱞᱟᱦᱟ ᱵᱟᱹᱠᱤ",sales:"ᱱᱤᱫᱟᱹ ᱠᱤᱨᱤᱱ",received:"ᱱᱤᱫᱟᱹ ᱧᱟᱢ",customers:"ᱜᱟᱦᱟᱠ",recent:"ᱱᱟᱣᱟ ᱠᱟᱹᱢᱤ",reports:"ᱨᱤᱯᱚᱨᱴ",khata:"ᱠᱷᱟᱛᱟ",all:"ᱡᱚᱛᱚ",due:"ᱵᱟᱹᱠᱤ",paid:"ᱯᱟᱹᱭ",people:"ᱜᱟᱦᱟᱠ",billssales:"ᱵᱤᱞ ᱟᱨ ᱠᱤᱨᱤᱱ",more:"ᱵᱟᱹᱲᱛᱤ",smartrcv:"ᱥᱢᱟᱨᱴ ᱨᱤᱥᱤᱵ",shopprofile:"ᱫᱩᱠᱟᱱ ᱯᱨᱚᱯᱷᱟᱭᱤᱞ",language:"ᱯᱟᱹᱨᱥᱤ",connect:"ᱜᱟᱦᱟᱠ ᱡᱚᱜᱟᱡᱚᱜ",login:"ᱞᱚᱜᱤᱱ",digitalpass:"ᱰᱤᱡᱤᱴᱟᱞ ᱮᱯ ᱯᱟᱥ",home:"ᱚᱲᱟᱜ",billsnav:"ᱵᱤᱞ",customer:"ᱜᱟᱦᱟᱠ",languageSet:"ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱱᱟ: "},
    Kashmiri:{greeting:"صبح بخیر 👋",glance:"تُہند دُکان ہُند نظر",outstanding:"وصول کرُن باقی",sales:"آجُک فروخت",received:"آج وصول",customers:"گاہک",recent:"حالیہ سرگرمی",reports:"رپورٹس",khata:"کھاتہ",all:"تمام",due:"بقایا",paid:"ادا",people:"گاہک",billssales:"بل تہ فروخت",more:"مزید",smartrcv:"اسمارٹ وصول",shopprofile:"دکان پروفائل",language:"زبان",connect:"گاہک رابطہ",login:"لاگ اِن",digitalpass:"ڈیجیٹل ایپ پاس",home:"ہوم",billsnav:"بل",customer:"گاہک",languageSet:"زبان منتخب: "}
  };
  const codes={English:"en",Telugu:"te",Hindi:"hi",Kannada:"kn",Marathi:"mr",Bengali:"bn",Assamese:"as",Gujarati:"gu",Malayalam:"ml",Punjabi:"pa",Odia:"or",Tamil:"ta",Urdu:"ur",Kashmiri:"ks",Konkani:"kok",Manipuri:"mni",Sanskrit:"sa",Maithili:"mai",Nepali:"ne",Sindhi:"sd",Dogri:"doi",Bodo:"brx",Santali:"sat"};
  const names={
    English:"English (english)",Telugu:"తెలుగు (telugu)",Hindi:"हिन्दी (hindi)",Kannada:"ಕನ್ನಡ (kannada)",Marathi:"मराठी (marathi)",Bengali:"বাংলা (bengali)",Assamese:"অসমীয়া (assamese)",Gujarati:"ગુજરાતી (gujarati)",Malayalam:"മലയാളം (malayalam)",Punjabi:"ਪੰਜਾਬੀ (punjabi)",Odia:"ଓଡ଼ିଆ (odia)",Tamil:"தமிழ் (tamil)",Urdu:"اردو (urdu)",Kashmiri:"کٲشُر (kashmiri)",Konkani:"कोंकणी (konkani)",Manipuri:"ꯃꯤꯇꯩ ꯂꯣꯟ (manipuri)",Sanskrit:"संस्कृतम् (sanskrit)",Maithili:"मैथिली (maithili)",Nepali:"नेपाली (nepali)",Sindhi:"سنڌي (sindhi)",Dogri:"डोगरी (dogri)",Bodo:"बड़ो (bodo)",Santali:"ᱥᱟᱱᱛᱟᱲᱤ (santali)"
  };
  const languageOrder=["English","Assamese","Bengali","Bodo","Dogri","Gujarati","Hindi","Kannada","Kashmiri","Konkani","Maithili","Malayalam","Manipuri","Marathi","Nepali","Odia","Punjabi","Sanskrit","Santali","Sindhi","Tamil","Telugu","Urdu"];
  const keys=languageOrder.filter(x=>T[x]);
  function current(){
    const saved=localStorage.getItem("dukaan_khata_language");
    if(keys.includes(saved))return saved;
    try{if(window.state?.settings&&keys.includes(window.state.settings.language))return window.state.settings.language}catch(e){}
    return "English";
  }
  window.applyLanguage=function(){
    const L=Object.assign({},T.English,T[current()]||{});
    const set=(sel,key)=>{const e=document.querySelector(sel);if(e&&L[key])e.textContent=L[key]};
    set("#greeting","greeting");set(".welcome h2","glance");set(".balance-hero span","outstanding");
    const stats=document.querySelectorAll(".stat span");["sales","received","customers"].forEach((k,i)=>{if(stats[i])stats[i].textContent=L[k]});
    const map=[["khata","khata"],["customers","people"],["bills","billssales"],["reports","reports"],["tools","more"]];
    map.forEach(([id,key])=>{const h=document.querySelector("#"+id+" .page-title h2");if(h)h.textContent=L[key]});
    document.querySelectorAll("#khata .segmented button").forEach((e,i)=>e.textContent=L[["all","due","paid"][i]]);
    const nav=document.querySelectorAll(".bottom-nav span");[L.home,L.khata,L.customer,L.billsnav,L.more].forEach((v,i)=>{if(nav[i])nav[i].textContent=v});
    document.querySelectorAll(".tools-grid button b").forEach((e,i)=>{const k=["smartrcv","shopprofile","language","connect","login","digitalpass"][i];if(k)e.textContent=L[k]});
    document.documentElement.lang=codes[current()]||"en";
  };
  window.setLanguage=function(x){
    if(!keys.includes(x))return;
    localStorage.setItem("dukaan_khata_language",x);
    try{if(window.state?.settings){window.state.settings.language=x;if(typeof window.saveState==="function")window.saveState()}}catch(e){}
    window.location.reload();
  };
  window.openLanguage=function(){
    const L=T[current()]||T.English;
    const nativeNames={English:"English",Hindi:"हिन्दी",Telugu:"తెలుగు",Kannada:"ಕನ್ನಡ",Marathi:"मराठी",Bengali:"বাংলা",Assamese:"অসমীয়া",Gujarati:"ગુજરાતી",Malayalam:"മലയാളം",Punjabi:"ਪੰਜਾਬੀ",Odia:"ଓଡ଼ିଆ",Tamil:"தமிழ்",Urdu:"اردو",Kashmiri:"کٲشُر",Konkani:"कोंकणी",Manipuri:"ꯃꯤꯇꯩ ꯂꯣꯟ",Sanskrit:"संस्कृतम्",Maithili:"मैथिली",Nepali:"नेपाली",Sindhi:"سنڌي",Dogri:"डोगरी",Bodo:"बड़ो",Santali:"ᱥᱟᱱᱛᱟᱲᱤ"};
    const options=keys.map(x=>{
      const native=nativeNames[x]||x;
      const selected=x===current();
      return '<button class="dk-lang-option" onclick="setLanguage(\\''+x+'\\')"><span class="dk-lang-flag">'+(x==="English"?"🇬🇧":"🇮🇳")+'</span><span class="dk-lang-name"><b>'+x+'</b><span class="dk-lang-arrow">→</span><small>'+native+'</small></span><i>'+ (selected?'✓':'○') +'</i></button>';
    }).join("");
    modal('<div class="dk-language-showcase">'+
      '<div class="dk-language-top"><button class="dk-language-back" onclick="closeModal()">‹</button><div class="dk-language-brand"><span>PERSONALIZE</span><h2>'+L.language+'</h2><small>Change app language</small></div><b class="dk-language-pro">✦ INDIA</b></div>'+
      '<div class="dk-language-world"><div class="dk-globe">🌍<i></i><em></em></div><div class="dk-orbit-label dk-orbit-en">🇬🇧 English</div><div class="dk-orbit-label dk-orbit-hi">🇮🇳 हिन्दी</div><div class="dk-orbit-label dk-orbit-te">🇮🇳 తెలుగు</div><div class="dk-orbit-label dk-orbit-kn">🇮🇳 ಕನ್ನಡ</div></div>'+
      '<div class="dk-language-panel"><div class="dk-language-panel-title"><span>🌐</span><div><b>Choose your language</b><small>Select one to personalize Dukaan Khata</small></div></div><div class="dk-language-list">'+options+'</div></div>'+
      '<div class="dk-language-save">🌐 <span>Your preferred language<br>will be saved automatically</span><b>✓</b></div>'+
      '<button class="dk-language-close" onclick="closeModal()">× Close</button></div>');
  };  document.addEventListener("DOMContentLoaded",()=>setTimeout(window.applyLanguage,100));
})();